```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(fig.align = "center",
                      out.width = "90%")
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_duo_accent(
  primary_color = "#071159",
  secondary_color = "#BEBEBE",
  inverse_header_color = "#071159"
)
```

```{r xaringanExtra, include=FALSE, warning=FALSE}

xaringanExtra::use_xaringan_extra(c("tile_view"))
```

```{r metathis, echo=FALSE}
library(metathis)
meta() %>%
  meta_name("github-repo" = "mariguilardi/Python-Brasil-2020-The-Carpentries") %>% 
  meta_social(
    title = "Ensino de programação: Como fazer parte da comunidade global The Carpentries?",
    description = paste(
      "Apresentação sobre ",
      "como fazer parte da comunidade global The Carpentries. "
    ),
    url = "https://mariguilardi.github.io/Python-Brasil-2020-The-Carpentries/index.html#1",
    image = "https://mariguilardi.github.io/Python-Brasil-2020-The-Carpentries/img/share-card.png",
    image_alt = paste(
      "Primeiro slide da apresentação sobre",
      "como fazer parte da comunidade global The Carpentries.",
      "Apresentado por Mariana Dias Guilardi e Beatriz Milz, na Python Brasil 2020."
    ),
    og_type = "website",
    og_author = c("Mariana Dias Guilardi", "Beatriz Milz"),
    twitter_card_type = "summary_large_image",
    twitter_creator = c("@mariguilardi", "@beamilz")
  )
```

```{r xaringanExtra-share-again, echo=FALSE}
xaringanExtra::use_share_again()
```

<!-- inicio font awesome -->
<script src="https://kit.fontawesome.com/1f72d6921a.js" crossorigin="anonymous"></script>
<!-- final font awesome -->

<!-- inicio github buttons  -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- final github buttons  -->
